name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ctech5
      FRONTEND_IMAGE: frontend
      BACKEND_IMAGE: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/frontend-deployment.yml
          kubectl apply -f kubernetes/backend-deployment.yml
          kubectl apply -f kubernetes/database-deployment.yml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
